config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  resources :tasks
  
  get "signup", to: "users#new"
  resources :users, only: [:create]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    
    belongs_to :user
    
    validates :content, presence: true, length: {maximum: 255}
    validates :status, presence: true, length: {maximum: 10}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password validations: true
    
    before_save { self.email.downcase! }
    
    validates :name,
        presence: true,
        length: {maximum: 50}
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email,
        presence: true,
        length: { maximum: 255},
        format: { with: VALID_EMAIL_REGEX, allow_blank: true},
        uniqueness: { case_sensitive: false }
    
    has_many :tasks
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    
    private
    
    def require_user_logged_in
        unless logged_in?
            redirect_to login_path
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password].downcase
    
    if login(email, password)
      flash[:success] = "ログインに成功しました"
      redirect_to root_path
    else
      flash[:danger] = "ログインに失敗しました"
      render :new
    end
    
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトに成功しました"
    redirect_to root_path
  end
  
  private
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      #ログイン成功
      session[:user_id] = @user.id
      return true
    else
      #ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_user_logged_in
    before_action :correct_user, only: [:show, :destroy, :edit, :update]
    
    def index
        current_user
    end
    
    def show
        @task = Task.find(params[:id])
    end
    
    def new
        #ユーザー情報がないから保存されないのを解決する必要がある
        @task = Task.new
    end
    
    def create
        @task = current_user.tasks.build(task_params)
        
        if @task.save
            flash[:success] = "Taskが正常に保存されました"
            redirect_to task_path(@task)
        else
            flash[:danger] = "Taskが保存されませんでした"
            render :new
        end
    end
    
    
    def edit
        @task = Task.find(params[:id])
    end
    
    def update
        @task = Task.find(params[:id])
        
        if @task.update(task_params)
            flash[:success] = "タスク内容は正常に更新されました"
            redirect_to task_path(@task)
        else
            flash.now[:danger] = "タスク内容は更新されませんでした"
            render :edit
        end
    end
    
    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        
        flash[:success] = "タスク内容は正常に削除されました"
        redirect_to tasks_url
    end
    
    private
    
    #StrongParameter
    def task_params
        params.require(:task).permit(:content, :status)
    end
    
    def correct_user
        @task = current_user.tasks.find_by(id: params[:id])
        unless @task
            redirect_to root_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザー登録に成功しました"
      redirect_to root_path
    else
      flash[:danger] = "ユーザー登録に失敗しました"
      render :new
    end
  end
  
  private
  #Strong Parameter
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/flash_messages" %>
    
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
    
    <% if task.errors.any? %>
        <div id="error_explanation">
            <ul>
                <% task.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <%= form.label :content, "タスク内容" %>
    <%= form.text_field :content %>
    
    <%= form.label :status, "ステータス" %>
    <%= form.text_field :status %>
    
    <%= form.submit "投稿" %>
    
<% end %>

app/views/tasks/edit.html.erb
<h1> id:<%= @task.id %>のタスク編集ページ</h1>

<%= render "form", task: @task %>

<%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/index.html.erb
<div>
    <h1>タスク一覧</h1>
    <table>
        <tr>
            <th>id</th>
            <th>タスクの内容</th>
            <th>ステータス</th>
        </tr>
        
        
        <% @current_user.tasks.each do |task| %>
            <tr>
                <td><%= link_to task.id, task_path(task) %></td>
                <td><%= task.content %></td>
                <td><%= task.status %></td>
            </tr>
        <% end %>
    </table>
    <%= link_to "新規作成", new_task_path %>
    <%= link_to "Logout", logout_path, method: :delete %>
</div>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render "form", task: @task %>

<%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> のタスク詳細ページ</h1>

<table>
    <tr>
        <th>id</th>
        <th>タスク内容</th>
        <th>ステータス</th>
        <th>書き込み日時</th>
        <th>編集日時</th>
    </tr>
    <tr>
        <td><%= @task.id %></td>
        <td><%= @task.content %></td>
        <td><%= @task.status %></td>
        <td><%= @task.created_at %></td>
        <td><%= @task.updated_at %></td>
    </tr>
</table>

<%= link_to "一覧に戻る", tasks_path %>
<%= link_to "このタスク内容を編集する", edit_task_path(@task) %>
<%= link_to "このタスクを削除する", @task, method: :delete, data: {confirm: "本当に削除してよろしいですか？"} %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
        <li>
            <%= msg %>
        </li>
    <% end %>
<% end %>
    
<h1>Sign up</h1>

<div>
    <%= form_with(model: @user, local: true) do |f| %>
    
        <div>
            <%= f.label :name, "Name" %>
            <%= f.text_field :name %>
        </div>

        <div>
            <%= f.label :email, "Email" %>
            <%= f.email_field :email %>
        </div>
        
        <div>
            <%= f.label :password, "Password" %>
            <%= f.password_field :password %>
        </div>
        
        <div>
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation %>
        </div>
        
        <%= f.submit "Sign up" %>
        
    <% end %>

    <p>Already signed up?? <%= link_to "Log in now!", login_path %></p>
    
</div>